# 🐼 Pandas I: Fundamentos y Manipulación de Datos

Esta sesión está pensada para un grupo con ritmo ágil.

## Objetivo
Pasar de archivos crudos a un flujo real de trabajo con pandas:
- cargar,
- inspeccionar,
- seleccionar,
- filtrar,
- transformar,
- ordenar,
- exportar.

## Estructura
Vamos a trabajar en bloques cortos de demostración + ejercicio práctico.

In [3]:
import pandas as pd
import numpy as np
from IPython.display import display

np.random.seed(42)

## 1️⃣ Series: la estructura más simple

Una **Series** es un array unidimensional con índice.

Puedes verla como una columna suelta con etiquetas.

In [4]:
values = [10, 20, 30, 40]
s_list = pd.Series(values, index=['a', 'b', 'c', 'd'])

data_dict = {'Apple': 100, 'Banana': 200, 'Cherry': 150}
s_dict = pd.Series(data_dict)

print(f"Series from list:\n{s_list}\n")
print(f"Series from dict:\n{s_dict}\n")
print(f"Index: {s_dict.index}")
print(f"Values: {s_dict.values}")

Series from list:
a    10
b    20
c    30
d    40
dtype: int64

Series from dict:
Apple     100
Banana    200
Cherry    150
dtype: int64

Index: Index(['Apple', 'Banana', 'Cherry'], dtype='str')
Values: [100 200 150]

### 🧠 Ejercicio 1: crea e inspecciona una Series

1. Crea una Series llamada `temperatures` con los valores `18, 21, 19, 24`.
2. Usa como índice `"Mon", "Tue", "Wed", "Thu"`.
3. Muestra el valor de `"Wed"`.
4. Muestra su índice y sus valores.

In [5]:
temperatures = pd.Series([18, 21, 19, 24], index=['Mon', 'Tue', 'Wed', 'Thu'])

print(temperatures)
print("Wed:", temperatures['Wed'])
print("Index:", temperatures.index)
print("Values:", temperatures.values)

Mon    18
Tue    21
Wed    19
Thu    24
dtype: int64
Wed: 19
Index: Index(['Mon', 'Tue', 'Wed', 'Thu'], dtype='str')
Values: [18 21 19 24]

## 2️⃣ DataFrames: la tabla de datos

Un **DataFrame** es una estructura bidimensional con filas y columnas.

Normalmente se crea a partir de un diccionario de listas.

In [6]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Paris', 'London', 'Tokyo'],
    'Salary': [50000, 60000, 70000, 80000],
}

df_manual = pd.DataFrame(data)
display(df_manual)
print("Shape:", df_manual.shape)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30     Paris   60000
2  Charlie   35    London   70000
3    David   40     Tokyo   80000

Shape: (4, 4)

### 🧠 Ejercicio 2: crea un DataFrame manualmente

Crea un DataFrame llamado `df_products` con estas columnas:
- `Product`
- `Price`
- `Stock`

Usa al menos 4 filas.

Después:
1. muéstralo,
2. imprime `shape`,
3. imprime solo los nombres de columnas.

In [7]:
df_products = pd.DataFrame({
    'Product': ['Keyboard', 'Mouse', 'Monitor', 'USB Hub'],
    'Price': [40, 25, 220, 35],
    'Stock': [15, 30, 8, 20],
})

display(df_products)
print("Shape:", df_products.shape)
print("Columns:", df_products.columns)

    Product  Price  Stock
0  Keyboard     40     15
1     Mouse     25     30
2   Monitor    220      8
3   USB Hub     35     20

Shape: (4, 3)
Columns: Index(['Product', 'Price', 'Stock'], dtype='str')

## 3️⃣ Lectura de archivos con pandas

Aquí es donde pandas empieza a ahorrar muchísimo tiempo.

Hoy vamos a cargar:
- CSV,
- JSON simple,
- JSON con lista de registros,
- Excel.

In [8]:
df_csv = pd.read_csv('personas.csv')
df_json_list = pd.read_json('personas.json')
df_json_single = pd.read_json('persona.json')

print("CSV loaded:")
display(df_csv)
print("JSON list loaded:")
display(df_json_list)
print("JSON single object loaded:")
display(df_json_single)

try:
    df_excel = pd.read_excel('Book1.xlsx')
    print("Excel loaded:")
    display(df_excel.head())
except Exception as exc:
    print("Excel could not be loaded:", exc)

CSV loaded:

  Nombre  Edad        Ciudad
0    Ana    25          Lima
1   Luis    30        Bogotá
2  María    22  Buenos Aires

JSON list loaded:

  nombre  edad                intereses
0    Ana    25  [lectura, programación]
1   Luis    30       [deportes, música]
2  María    22             [arte, cine]

JSON single object loaded:

  nombre  edad     intereses
0    Ana    25       lectura
1    Ana    25  programación

Excel loaded:

   nombre  edad  altura
0    Alex    25     180
1  Alonso    26     187
2   María    24     175
3   Paula    23     160

### 🧠 Ejercicio 3: carga y compara formatos

1. Carga `personas.csv` en un DataFrame llamado `people_csv`.
2. Carga `personas.json` en un DataFrame llamado `people_json`.
3. Muestra `shape` de ambos.
4. Muestra las 2 primeras filas de cada uno.

In [9]:
people_csv = pd.read_csv('personas.csv')
people_json = pd.read_json('personas.json')

print("CSV shape:", people_csv.shape)
print("JSON shape:", people_json.shape)
print()
display(people_csv.head(2))
display(people_json.head(2))

CSV shape: (3, 3)
JSON shape: (3, 3)

  Nombre  Edad  Ciudad
0    Ana    25    Lima
1   Luis    30  Bogotá

  nombre  edad                intereses
0    Ana    25  [lectura, programación]
1   Luis    30       [deportes, música]

## 4️⃣ Inspección: mirar antes de tocar

Antes de hacer análisis o limpieza, hay que responder rápido:
- ¿cuántas filas y columnas hay?
- ¿qué tipos tengo?
- ¿qué aspecto tienen los datos?

In [10]:
df_large = pd.DataFrame(
    np.random.randint(0, 100, size=(100, 5)),
    columns=['A', 'B', 'C', 'D', 'E']
)

display(df_large.head(3))
display(df_large.tail(3))
print("Shape:", df_large.shape)
print("Rows:", df_large.shape[0])
print("Columns:", df_large.shape[1])
print()
df_large.info()
print()
display(df_large.describe())

    A   B   C   D   E
0  51  92  14  71  60
1  20  82  86  74  74
2  87  99  23   2  21

     A   B   C   D   E
97  57   0  33  95  47
98  88   0  15  60  63
99  62  68  21  92  66

Shape: (100, 5)
Rows: 100
Columns: 5

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       100 non-null    int64
 1   B       100 non-null    int64
 2   C       100 non-null    int64
 3   D       100 non-null    int64
 4   E       100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB

               A           B           C           D           E
count  100.00000  100.000000  100.000000  100.000000  100.000000
mean    46.64000   46.230000   51.380000   53.780000   46.340000
std     29.55991   30.502146   30.287771   28.958549   28.246112
min      0.00000    0.000000    0.000000    1.000000    0.000000
25%     21.50000   18.750000   22.750000   29.000000   24.000000
50%     50.00000   43.500000   53.500000   60.000000   44.000000
75%     66.75000   72.500000   78.000000   76.250000   66.000000
max     99.00000   99.000000   98.000000   98.000000   98.000000

### 🧠 Ejercicio 4: radiografía rápida del DataFrame

Usando `df_large`:
1. muestra las 5 primeras filas,
2. muestra las 5 últimas,
3. imprime `shape`,
4. imprime solo el número de filas usando `shape[0]`,
5. imprime `dtypes`.

In [11]:
display(df_large.head())
display(df_large.tail())
print("Shape:", df_large.shape)
print("Rows:", df_large.shape[0])
print(df_large.dtypes)

    A   B   C   D   E
0  51  92  14  71  60
1  20  82  86  74  74
2  87  99  23   2  21
3  52   1  87  29  37
4   1  63  59  20  32

     A   B   C   D   E
95  91  57  54  89  89
96  61  22   8  11   0
97  57   0  33  95  47
98  88   0  15  60  63
99  62  68  21  92  66

Shape: (100, 5)
Rows: 100
A    int64
B    int64
C    int64
D    int64
E    int64
dtype: object

## 5️⃣ Selección e indexación

Aquí está uno de los núcleos de la clase:
- `df['columna']` para columnas,
- `df[['col1', 'col2']]` para varias columnas,
- `.iloc` por posición,
- `.loc` por etiqueta.

In [12]:
col_a = df_large['A']
cols_subset = df_large[['A', 'C', 'E']]

display(cols_subset.head(3))
display(df_large.iloc[0:5, 0:3])
display(df_large.loc[0:5, ['A', 'D']])
print("Value at iloc[10, 2]:", df_large.iloc[10, 2])
print("Value at loc[0, 'A']:", df_large.loc[0, 'A'])

    A   C   E
0  51  14  60
1  20  86  74
2  87  23  21

    A   B   C
0  51  92  14
1  20  82  86
2  87  99  23
3  52   1  87
4   1  63  59

    A   D
0  51  71
1  20  74
2  87   2
3  52  29
4   1  20
5  75  88

Value at iloc[10, 2]: 88
Value at loc[0, 'A']: 51

### 🧠 Ejercicio 5: selección

Usando `df_large`:
1. selecciona las columnas `B` y `E`,
2. muestra las filas 50 a 55 usando `.iloc`,
3. muestra el valor de la fila `0` y la columna `A` usando `.loc`,
4. selecciona filas 10 a 15 y columnas `C` y `D`.

In [13]:
cols_subset = df_large[['B', 'E']]
rows_subset = df_large.iloc[50:56, :]
value = df_large.loc[0, 'A']
subset_cd = df_large.loc[10:15, ['C', 'D']]

display(cols_subset.head())
display(rows_subset)
print("Value at [0, 'A']:", value)
display(subset_cd)

    B   E
0  92  60
1  82  74
2  99  21
3   1  37
4  63  32

     A   B   C   D   E
50  10  15  96  72  58
51  69  79  92   2  19
52  58  35  18  89  66
53  18  19  95  70  51
54  32  39  38  81   0
55  10  91  56  88  49

Value at [0, 'A']: 51

     C   D
10  88  59
11  52   1
12  70  43
13  77  80
14   1   5
15  92  62

## ☕ Descanso sugerido (15 min)

Aquí ya deberían saber cargar, inspeccionar y seleccionar.

## 6️⃣ Filtrado y transformación

El patrón más común en trabajo real es:
1. filtrar filas,
2. crear columnas nuevas,
3. volver a filtrar,
4. quedarte solo con lo útil.

In [14]:
mask = df_large['A'] > 50
filtered_df = df_large[mask]

print("Original rows:", df_large.shape[0])
print("Filtered rows:", filtered_df.shape[0])

complex_filter = df_large[(df_large['A'] > 50) & (df_large['B'] < 20)]
display(complex_filter.head())

df_large['Suma'] = df_large['A'] + df_large['B']
display(df_large.head())

Original rows: 100
Filtered rows: 49

     A   B   C   D   E
3   52   1  87  29  37
7   79  14  61  61  46
17  99  13  94  47  14
23  62  10  80   7  34
39  76   2  69  71  26

    A   B   C   D   E  Suma
0  51  92  14  71  60   143
1  20  82  86  74  74   102
2  87  99  23   2  21   186
3  52   1  87  29  37    53
4   1  63  59  20  32    64

In [15]:
df_large['Total_AB'] = df_large['A'] + df_large['B']
filtered_a = df_large[df_large['A'] > 50]
filtered_complex = df_large[(df_large['A'] > 50) & (df_large['B'] < 20)]
result_subset = filtered_complex[['A', 'B', 'Total_AB']]

display(filtered_a.head())
display(filtered_complex.head())
display(result_subset.head())

    A   B   C   D   E  Suma  Total_AB
0  51  92  14  71  60   143       143
2  87  99  23   2  21   186       186
3  52   1  87  29  37    53        53
5  75  57  21  88  48   132       132
6  90  58  41  91  59   148       148

     A   B   C   D   E  Suma  Total_AB
3   52   1  87  29  37    53        53
7   79  14  61  61  46    93        93
17  99  13  94  47  14   112       112
23  62  10  80   7  34    72        72
39  76   2  69  71  26    78        78

     A   B  Total_AB
3   52   1        53
7   79  14        93
17  99  13       112
23  62  10        72
39  76   2        78

In [16]:
# Your code here

## 7️⃣ Ordenación

Después de seleccionar y filtrar, normalmente queremos ordenar resultados.

Podemos ordenar por una o varias columnas, y decidir el sentido de cada una.

In [17]:
df_sorted = df_large.sort_values(by='A', ascending=True)
df_multi_sort = df_large.sort_values(by=['A', 'B'], ascending=[False, True])

display(df_sorted.head())
display(df_multi_sort.head())

    A   B   C   D   E  Suma  Total_AB
46  0  18   1  52  43    18        18
58  0  47  11  68  36    47        47
4   1  63  59  20  32    64        64
29  2   0   4  89  13     2         2
15  3  53  92  62  17    56        56

     A   B   C   D   E  Suma  Total_AB
17  99  13  94  47  14   112       112
65  99  32  67  32  13   131       131
70  97  20  29  96  27   117       117
42  95  87  51  61  57   182       182
78  94  53  57  66  45   147       147

In [18]:
sort_a_desc = df_large.sort_values(by='A', ascending=False)
sort_ab = df_large.sort_values(by=['A', 'B'], ascending=[False, True])

display(sort_a_desc.head())
display(sort_ab.head())

     A   B   C   D   E  Suma  Total_AB
17  99  13  94  47  14   112       112
65  99  32  67  32  13   131       131
70  97  20  29  96  27   117       117
42  95  87  51  61  57   182       182
78  94  53  57  66  45   147       147

     A   B   C   D   E  Suma  Total_AB
17  99  13  94  47  14   112       112
65  99  32  67  32  13   131       131
70  97  20  29  96  27   117       117
42  95  87  51  61  57   182       182
78  94  53  57  66  45   147       147

In [19]:
# Your code here

## 🏆 Práctica Final

Usando `df_large`:

1. Crea una nueva columna llamada `Suma` que sea `A + B`.
2. Filtra las filas donde `Suma` sea mayor a `100`.
3. Quédate solo con las columnas `A`, `B`, `C` y `Suma`.
4. Ordena el resultado por la columna `C` de forma descendente.
5. Guarda el resultado en un archivo `resultado.csv`.

In [20]:
df_large['Suma'] = df_large['A'] + df_large['B']
filtered_df = df_large[df_large['Suma'] > 100]
final_df = filtered_df[['A', 'B', 'C', 'Suma']].sort_values(by='C', ascending=False)
final_df.to_csv('resultado.csv', index=False)

display(final_df.head())
print("Saved as resultado.csv")

     A   B   C  Suma
62  37  83  98   120
86  14  91  97   105
17  99  13  94   112
51  69  79  92   148
45  91  53  86   144

Saved as resultado.csv